# A docker-compose file aimed at aiding development
version: "3.5"
services:
  pgadmin:
    image: dpage/pgadmin4:6.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 5050:80
    restart: unless-stopped
