version: "3.5"
services:
  timeline-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=timeline
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_persistence:/var/lib/postgresql/data
    restart: unless-stopped
  timeline-backend:
    build: backend
    environment:
      - BACKEND_DEBUG
      - BACKEND_SECRET_KEY
      - FRONTEND_CLIENT_ID
      - FRONTEND_DOMAIN
    depends_on:
      - timeline-db
    volumes:
      - ./backend/source:/usr/src/app
      - archives:/data/archives
      - backups:/data/backups
      - previews:/assets/previews
      - backend_staticfiles:/assets/static
      - ssh_keys:/root/.ssh
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
  timeline-frontend:
    build:
      context: frontend
      args:
        - FRONTEND_CLIENT_ID
        - FRONTEND_DOMAIN
        - GOOGLE_MAPS_API_KEY
    volumes:
      - ./frontend/source:/usr/share/nginx/html:ro
    depends_on:
      - timeline-backend
    logging:
      driver: "none"
    restart: unless-stopped
  mqtt-broker:
    build: mqtt-broker
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
    volumes:
      - mqtt_persistence:/mosquitto/data
    ports:
      - 1883:1883
    restart: unless-stopped
  geolocation-client:
    build: geolocation-client
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - GEOLOCATION_CLIENT_ID
      - GEOLOCATION_CLIENT_SECRET
    depends_on:
      - mqtt-broker
      - timeline-backend
    volumes:
      - ./geolocation-client/source:/usr/src/app
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
  proxy:
    build: proxy
    depends_on:
      - timeline-frontend
      - timeline-backend
    volumes:
      - archives:/data/archives
      - backups:/data/backups
      - previews:/assets/previews
      - backend_staticfiles:/assets/static
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
volumes:
  db_persistence:
  mqtt_persistence:
  backups:
  archives:
  previews:
  ssh_keys:
  backend_staticfiles:
