# Generated by Django 3.1.2 on 2021-01-25 16:36

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTakeoutArchive',
            fields=[
                ('key', models.SlugField(allow_unicode=True, max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField()),
                ('archive_file', models.FileField(upload_to=archive.models.archive_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
