# Generated by Django 3.1.2 on 2021-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletakeoutarchive',
            name='date_processed',
            field=models.DateTimeField(null=True),
        ),
    ]
