# Generated by Django 3.1.2 on 2021-02-03 12:33

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20210125_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterArchive',
            fields=[
                ('key', models.SlugField(allow_unicode=True, max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
                ('archive_file', models.FileField(upload_to=archive.models.archive_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
