# Generated by Django 3.1.2 on 2021-02-06 09:49

from django.db import migrations, models

import archive.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_jsonarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpxArchive',
            fields=[
                ('key', models.SlugField(allow_unicode=True, max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
                ('archive_file', models.FileField(upload_to=archive.models.base.archive_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
