# Generated by Django 3.1.2 on 2021-05-27 10:36

import archive.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20210502_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramArchive',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
                ('archive_file', models.FileField(upload_to=archive.models.base.archive_path)),
                ('include_supergroup_chats', models.BooleanField(default=False, verbose_name='Include supergroup chats')),
                ('include_group_chats', models.BooleanField(default=True, verbose_name='Include private group chats')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
