# Generated by Django 3.1.2 on 2021-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_telegramarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramarchive',
            name='include_group_chats',
            field=models.BooleanField(default=True, verbose_name='Include group chats'),
        ),
    ]
