# Generated by Django 3.1.2 on 2021-06-14 12:53

import archive.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20210603_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookArchive',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
