# Generated by Django 3.1.2 on 2022-01-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_auto_20210716_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICalendarArchive',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
