# Generated by Django 3.1.2 on 2022-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20220516_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditArchive',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField(null=True)),
                ('date_until', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('date_processed', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
