# Generated by Django 3.1.2 on 2020-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20201021_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=50)),
                ('consumer_secret', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
                ('access_token_secret', models.CharField(max_length=50)),
                ('twitter_username', models.CharField(max_length=50)),
            ],
        ),
    ]
