# Generated by Django 3.1.2 on 2020-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_hackernewssource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField()),
            ],
        ),
    ]
