# Generated by Django 3.1.2 on 2021-03-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_auto_20210316_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='/srv/mounts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
