# Generated by Django 3.1.2 on 2021-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_filesystemsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemsource',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/data/mounts'),
        ),
    ]
