# Generated by Django 3.1.2 on 2022-04-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0017_gitsource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RsyncDestination',
        ),
    ]
