# Generated by Django 3.1.2 on 2020-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveSmallIntegerField(default=22)),
                ('path', models.TextField()),
            ],
        ),
    ]
