# Generated by Django 3.1.2 on 2020-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsource',
            name='key',
            field=models.CharField(default='tmp', max_length=80),
            preserve_default=False,
        ),
    ]
