# Generated by Django 3.1.2 on 2020-10-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_backupsource_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsource',
            name='key',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
