# Generated by Django 3.1.2 on 2020-12-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_redditsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackernews_username', models.CharField(max_length=20)),
            ],
        ),
    ]
