# Generated by Django 3.1.2 on 2021-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_rsssource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackupSource',
            new_name='RsyncSource',
        ),
    ]
