# Generated by Django 3.1.2 on 2021-04-08 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_auto_20210408_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsyncDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('path', models.TextField()),
                ('key', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
