# Generated by Django 3.1.2 on 2021-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_rsyncdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsyncdestination',
            name='key_exchange_method',
            field=models.CharField(choices=[('hetzner', 'hetzner'), ('ssh-copy-id', 'ssh-copy-id')], default='ssh-copy-id', max_length=20),
        ),
        migrations.AddField(
            model_name='rsyncsource',
            name='key_exchange_method',
            field=models.CharField(choices=[('hetzner', 'hetzner'), ('ssh-copy-id', 'ssh-copy-id')], default='ssh-copy-id', max_length=20),
        ),
    ]
