# Generated by Django 3.1.2 on 2021-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_auto_20210502_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystemsource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hackernewssource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='redditsource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rsssource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rsyncdestination',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rsyncsource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='twittersource',
            name='id',
        ),
        migrations.AlterField(
            model_name='filesystemsource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hackernewssource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redditsource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsssource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsyncdestination',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rsyncsource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twittersource',
            name='key',
            field=models.SlugField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
