# Generated by Django 3.1.2 on 2022-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_auto_20210502_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitSource',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('repo_url', models.URLField()),
                ('author_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['key'],
                'abstract': False,
            },
        ),
    ]
