# Generated by Django 3.1.2 on 2022-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0018_rename_backups_to_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RsyncDestination',
        ),
    ]
