# Generated by Django 3.1.2 on 2022-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0019_delete_rsyncdestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraktSource',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('access_token_created', models.DateTimeField(null=True)),
                ('access_token_expires', models.DateTimeField(null=True)),
                ('client_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
