# Generated by Django 3.1.2 on 2022-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0020_traktsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystemsource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='filesystemsource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gitsource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gitsource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackernewssource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hackernewssource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redditsource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redditsource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rsssource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rsssource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rsyncsource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rsyncsource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traktsource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traktsource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twittersource',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twittersource',
            name='date_until',
            field=models.DateTimeField(null=True),
        ),
    ]
