# Generated by Django 3.1.2 on 2022-04-19 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RsyncDestination',
            fields=[
                ('user', models.CharField(max_length=80)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=22, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('path', models.TextField()),
                ('key_exchange_method', models.CharField(choices=[('hetzner', 'hetzner'), ('ssh-copy-id', 'ssh-copy-id')], default='ssh-copy-id', max_length=20)),
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
