# Generated by Django 3.1.2 on 2020-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20201020_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
