# Generated by Django 3.1.2 on 2020-11-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20201020_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_modified',
        ),
    ]
