# Generated by Django 3.1.2 on 2021-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_remove_entry_date_modified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['schema'], name='timeline_en_schema_e31fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-date_on_timeline'], name='timeline_en_date_on_861bc0_idx'),
        ),
    ]
