# Generated by Django 3.1.2 on 2021-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_source_name_fix'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entry',
            name='timeline_en_date_on_861bc0_idx',
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['date_on_timeline'], name='timeline_en_date_on_d4f91d_idx'),
        ),
    ]
