#!/bin/bash
# Performs backup to remote host using rsync. Respects a .rsyncignore file.
# Usage:
#    incremental-backup [src-dir] [dest-dir]
# Arguments:
#    - src-dir is a regular path, preferably absolute
#    - dest-dir is a relative path to the root backup dir, e.g. "servers/test.com"

set -o errexit
set -o nounset
set -o pipefail

readonly SOURCE_DIR="$1"
readonly DATETIME="$(date '+%Y-%m-%d_%H:%M:%S')"
readonly DESTINATION_DIR="/home/backups/$2"
readonly REMOTE_PATH="backups@home.nicolasbouliane.com:${DESTINATION_DIR}"
readonly REMOTE_PORT="2200"

# Sync files to /[backups root]/[src-dir]
# Ignores files listed in .rsyncignore
rsync -avzL \
  --rsync-path="mkdir -p ${DESTINATION_DIR} && rsync" \
  -e "ssh -p ${REMOTE_PORT}" --delete \
  --filter=":- .rsyncignore" \
  "${SOURCE_DIR}/" \
  "${REMOTE_PATH}"